### ISSUE TITLE
When running in a clustered setup ( replica count set to at least 2 ), token issuance is not respected.

### ISSUE THREAD

**Issue by nstankov-bg** [MedAziz11/Uptime-Kuma-Web-API#27]
Take this example yaml.

Simple test in docker swarm via [Traefik](https://dockerswarm.rocks/traefik/)

```yaml
version: '3.9'

services:
  uptime-kuma:
    image: louislam/uptime-kuma:1.21.2-alpine
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      update_config:
        order: start-first
        parallelism: 1
        delay: 10s
        failure_action: rollback
        monitor: 60s
        max_failure_ratio: 0.3
    image: louislam/uptime-kuma:1.21.2-alpine
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      update_config:
        order: start-first
        parallelism: 1
        delay: 10s
        failure_action: rollback
        monitor: 60s
        max_failure_ratio: 0.3
      placement:
         constraints: [node.labels.web-node == true]
      labels:
        # Enable Traefik for this service, to make it available in the public network
        - traefik.enable=true
        # Use the traefik-public network (declared below)
        - traefik.docker.network=traefik-public
        - traefik.constraint-label=traefik-public
        # https-redirect middleware to redirect HTTP to HTTPS
        # It can be re-used by other stacks in other Docker Compose files
        - traefik.http.middlewares.https-redirect.redirectscheme.scheme=https
        - traefik.http.middlewares.https-redirect.redirectscheme.permanent=true
        # traefik-http set up only to use the middleware to redirect to https
        - traefik.http.routers.kuma-http.rule=Host(`uptime-dev.example.com`)
        - traefik.http.routers.kuma-http.entrypoints=http
        # Middlewares #
        - traefik.http.routers.kuma-http.middlewares=https-redirect,example-ipwhitelist@docker
        - traefik.http.routers.kuma-https.middlewares=example-ipwhitelist@docker
        # traefik-https the actual router using HTTPS
        - traefik.http.routers.kuma-https.rule=Host(`uptime-dev.example.com`)
        - traefik.http.routers.kuma-https.entrypoints=https
        - traefik.http.routers.kuma-https.tls=true
        # Use the special Traefik service api@internal with the web UI/Dashboard
        # Use the "le" (Let's Encrypt) resolver created below
        - traefik.http.routers.kuma-https.tls.certresolver=le
        # Enable HTTP Basic auth, using the middleware created above
        # Define the port inside of the Docker service to use
        - traefik.http.services.kuma-service.loadbalancer.server.port=3001
    healthcheck:
      test: "wget --spider --quiet http://localhost:3001 || exit 1"
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 120s
    networks:
      - traefik-public
      - kuma-internal
    volumes:
      - "/nfs_data/status_example_com/app/data:/app/data" #owned by user 1000 on NFS

  uptime-kuma-api:
    image: registry.example.com/devops/uptime-kuma-web-api:0.4
    restart: always
    volumes:
      - /nfs_data/status_example_com/api/db:/db/ # Owned by app user in container (POSIX)
    environment:
      - KUMA_SERVER=${KUMA_SERVER:-http://uptime-kuma:3001}
      - KUMA_USERNAME=${KUMA_USERNAME:-admin}
      - KUMA_PASSWORD=${KUMA_PASSWORD}
      - ADMIN_PASSWORD=${ADMIN_PASSWORD}
      - ACCESS_TOKEN_EXPIRATION=${ACCESS_TOKEN_EXPIRATION:-5}
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      update_config:
        order: start-first
        parallelism: 1
        delay: 10s
        failure_action: rollback
        monitor: 60s
        max_failure_ratio: 0.3
      placement:
         constraints: [node.labels.web-node == true]
      labels:
        # Enable Traefik for this service, to make it available in the public network
        - traefik.enable=true
        # Use the traefik-public network (declared below)
        - traefik.docker.network=traefik-public
        - traefik.constraint-label=traefik-public
        # https-redirect middleware to redirect HTTP to HTTPS
        # It can be re-used by other stacks in other Docker Compose files
        - traefik.http.middlewares.https-redirect.redirectscheme.scheme=https
        - traefik.http.middlewares.https-redirect.redirectscheme.permanent=true
        # traefik-http set up only to use the middleware to redirect to https
        - traefik.http.routers.kuma-api-http.rule=Host(`uptime-dev-api.example.com`)
        - traefik.http.routers.kuma-api-http.entrypoints=http
        # Middlewares #
        - traefik.http.routers.kuma-api-http.middlewares=https-redirect,example-ipwhitelist@docker
        - traefik.http.routers.kuma-api-https.middlewares=example-ipwhitelist@docker
        # traefik-https the actual router using HTTPS
        - traefik.http.routers.kuma-api-https.rule=Host(`uptime-dev-api.example.com`)
        - traefik.http.routers.kuma-api-https.entrypoints=https
        - traefik.http.routers.kuma-api-https.tls=true
        # Use the special Traefik service api@internal with the web UI/Dashboard
        # Use the "le" (Let's Encrypt) resolver created below
        - traefik.http.routers.kuma-api-https.tls.certresolver=le
        # Enable HTTP Basic auth, using the middleware created above
        # Define the port inside of the Docker service to use
        - traefik.http.services.kuma-api-service.loadbalancer.server.port=8000
    networks:
      - traefik-public
      - kuma-internal
```

When hitting two replicas via non-sticky load-balancer, the token seems to be invalid.
I think there is some dependency on the individual container's validation of the token, that is currently not suited for a stateless environment.

Will investigate.
